### PR TITLE
Fix: Heroku deployment

### LINKED ISSUE #54: Fix: Heroku deployment
## Issue

App is not running in the Heroku
 
## Expected

App should be run properly in the Heroku
 
## Steps to reproduce

Visit https://nimble-google-scraper-staging.herokuapp.com/

### PR DESCRIPTION
**Pull request by junan**
https://github.com/junan/google-scraper/projects/1#card-58504471

## What happened 👀

Fixed the Heroku deployment and the app running in the Heroku properly

## Insight 📝

- Used postgres as session store insted of `redis`. Becuase Beego use [go-redis](https://github.com/go-redis/redis/issues/864) and it does not work with `Heroku REDIS_URL`
- Removed `akhileshns/heroku-deploy@v3.7.8` github action package as I can't run Heroku `worker` with it and used `Dockerfile.worker`

## Proof Of Work 📹

Deployed and running properly https://nimble-google-scraper-staging.herokuapp.com/

### CODE REVIEW

File: database/redis.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ func GetRedisUrl() (redis.Conn, error) {
 		logs.Critical("Redis url not found: ", err)
 	}
 
-	return redis.Dial("tcp", redisUrl)
+	return redis.DialURL(redisUrl)
```
Comment (junan) [inline database/redis.go:32]: `Dial` does not [work](https://github.com/gomodule/redigo/issues/257#issuecomment-308867661) with the Heroku REDIS_URL

Comment (gutakk) [reply database/redis.go:32]: What is the error?

Comment (junan) [reply database/redis.go:32]: @gutakk The error was `too many colons in address` and it cant connect with the `redis`

Comment (gutakk) [reply database/redis.go:32]: In case you still want to use redis, maybe you can take a look at my [redis connection ](https://github.com/gutakk/go-google-scraper/blob/master/db/redis.go#L29). Redigo also cannot connect to heroku redis with the same error as yours.

File: Dockerfile.worker [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+
+WORKDIR /app
+
+COPY . .
+
+RUN go mod download
+
+WORKDIR /app/worker
+
+RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
```
Comment (Lahphim) [inline Dockerfile.worker:11]: @junan Why do we need to assign here again as we already had here ?
```
ENV GO111MOD=on \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64
  ```

File: Makefile [hunk 3]
```diff
@@ -11,8 +19,15 @@ build-assets:
...
 
+db-migrate:
+	bee migrate -driver=postgres -conn="$(DATABASE_URL)"
+
+db-rollback:
+	bee migrate rollback -driver=postgres -conn="$(DATABASE_URL)"
+
 dev:
 	docker-compose -f docker-compose.dev.yml up -d
+	make db-migrate
```
Comment (Lahphim) [inline Makefile:30]: @junan Won't you have any issues with `database not found` or something about database issues around here?

cc: @carryall

File: Procfile [hunk 4]
```diff
@@ -0,0 +1,2 @@
+worker: go run ./main.go
```
Comment (Lahphim) [inline Procfile:1]: @junan Where will you use this one?

File: database/redis.go (hunk 1 above)
Comment (Lahphim) [reply database/redis.go:32]: Yeah, I've heard some issue about `redis connection` issue from Hoang also.
Maybe Hoang might know the solution 🍀

Comment (junan) [reply database/redis.go:32]: Here is our post discussion on slack cc @Lahphim 
Screen Shot 2021-04-09 at 3 15 13 PM

File: Makefile (hunk 3 above)
Comment (carryall) [reply Makefile:30]: @Lahphim @junan The issue I got earlier is when we build the database container for the first time and run the migration right after the `docker-compose` command the migration command would fail because it cannot find the database yet. So I have to provide 2 make commands, one for preparing the database container and another one for the migration. 💭

File: Procfile (hunk 4 above)
Comment (junan) [reply Procfile:1]: It will run the worker, https://github.com/junan/google-scraper/blob/develop/worker/main.go

File: Makefile (hunk 3 above)
Comment (junan) [reply Makefile:30]: Screen Shot 2021-04-09 at 3 22 58 PM

@Lahphim Its works fine for me locally and staging

File: database/redis.go (hunk 1 above)
Comment (hoangmirs) [reply database/redis.go:32]: Yes, I faced this and solved it by adding [redisurl](github.com/soveran/redisurl) to get the correct information (Gut suggested me to use it).
But good to know that `redigo` has `DialURL()` and it did the same thing like `redisurl` 😄

Comment (junan) [reply database/redis.go:32]: @hoangmirs Yes Hoàng , I found it in [here](https://github.com/gomodule/redigo/issues/257#issuecomment-308867661) to using `DialURL()` 😄

File: .github/workflows/deploy.yml [hunk 5]
```diff
@@ -34,11 +37,36 @@ jobs:
...
+          docker-compose build --build-arg DATABASE_URL=$DATABASE_URL
+          docker-compose push app
+
+      - name: Log in to Heroku container
+        run: heroku container:login
+
+      - name: Publish application
+        run: |
+          heroku container:push --recursive -a $HEROKU_APP_NAME
+          heroku container:release web worker -a $HEROKU_APP_NAME
```
Comment (gutakk) [inline .github/workflows/deploy.yml:72]: Does `heroku container:push` and `heroku container:release` looking for `Dockerfile` instead of `Dockerfile.web` for web process? I found [this](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-multiple-images) in the heroku documentation but still not sure.

File: Procfile (hunk 4 above)
Comment (gutakk) [reply Procfile:1]: Where do you use this `Procfile`?
In the `Makefile` you use `go run worker/main.go` to start worker and `bee run` to start the application.

**Review by Lahphim — APPROVED** [review]

File: Procfile (hunk 4 above)
Comment (Lahphim) [reply Procfile:1]: @gutakk

Comment (junan) [reply Procfile:1]: My `Dockerfile.worker` ENTRYPOINT is  `["/app/worker/worker"]`. So it runs the the workers `main.go`

Comment (gutakk) [reply Procfile:1]: As discussed in slack, Procfile is used on Heroku only.

File: .github/workflows/deploy.yml (hunk 5 above)
Comment (junan) [reply .github/workflows/deploy.yml:72]: For  ~`web` process it looks for `Dockerfile`~ and for `worker` process it looks for `Dockerfile.worker`. I updated `Dockerfile` to `Dockerfile.web` as Heroku web process looks for `Dockerfile.web`

**Review by gutakk — APPROVED** [review]
